cms/urls.py
from django.contrib import admin
from django.urls import path
from datawork import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="homepage"),
    path('apply/', views.apply, name="apply"),
    path('student/login/', views.student_login, name="student_login"),
    path('student/logout/', views.logout, name="student_logout"),
    path('student/dashboard/', views.student_dashboard, name="student_dashboard"),
    path('student/payment/', views.student_payment, name="student_payment"),
    path('student/payment/<int:pay_id>/done', views.payment_done, name="student_payment_done"),
    path('student/course/', views.student_course, name="student_course"),
    path('student/setting/', views.student_setting, name="student_setting"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

datawork/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


class Course(models.Model):
    course_id = models.AutoField(primary_key=True)
    course_title = models.CharField(max_length=200)
    course_duration = models.CharField(max_length=200)
    course_fees = models.IntegerField()
    course_desc = models.TextField()

    def __str__(self):
        return self.course_title


class Student(models.Model):
    roll = models.AutoField(primary_key=True)
    full_name = models.CharField(max_length=200)
    father_name = models.CharField(max_length=200)
    contact = models.IntegerField()
    email = models.EmailField()
    dp = models.ImageField(upload_to="student/")
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    state = models.CharField(max_length=200)
    dob = models.DateField()
    status = models.IntegerField(default=0)
    date_of_creation = models.DateTimeField(default=timezone.now)
    password = models.CharField(max_length=200)

    def __str__(self):
        return self.full_name


class StudentCourse(models.Model):
    studentCourse_id = models.AutoField(primary_key=True)
    course_id = models.ForeignKey(Course, on_delete=models.CASCADE)
    student_id = models.ForeignKey(Student, on_delete=models.CASCADE)
    type = models.IntegerField()

    def __str__(self):
        return self.course_id.course_title


class Payment(models.Model):
    pay_id = models.AutoField(primary_key=True)
    payment_student_id = models.ForeignKey(Student, on_delete=models.CASCADE)
    MONTHS = (("1","Jan"),("2","Feb"),("3","March"),("4","Apr"),("5","May"),("6","June"),("7","July"),
              ("8","Aug"),("9","Sep"),("10","Oct"),("11","Nov"),("12","Dec"))
    payment_month = models.CharField(max_length=200,choices=MONTHS)
    payment_amount = models.IntegerField()
    payment_status = models.IntegerField(default=0)
    payment_doc = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.payment_student_id.full_name

datawork/forms.py
from django import forms
from .models import *


class InsertStudent(forms.ModelForm):
    class Meta:
        model = Student
        exclude = ('date_of_creation', 'status')


class InsertCourse(forms.ModelForm):
    class Meta:
        model = Course
        fields = '__all__'


class InsertStudentCourse(forms.ModelForm):
    class Meta:
        model = StudentCourse
        fields = '__all__'

datawork/views.py
from django.shortcuts import render, redirect
from .forms import *
from django.db.models import Q, Sum
# Create your views here.


def home(r):
    return render(r, 'home.html')


def apply(r):
    form = InsertStudent(r.POST or None, r.FILES or None)
    data = {"insert_form": form}
    if r.method == "POST":
        if form.is_valid():
            form.save()
            return redirect(apply)
        else:
            return render(r, 'apply.html', data)
    return render(r, 'apply.html', data)


def student_login(r):
    if r.method == 'POST':
        email = r.POST.get('email')
        password = r.POST.get('password')
        condition = (Q(email=email) & Q(password=password))
        check = Student.objects.filter(condition).count()
        if check > 0:
            r.session['student_log'] = email
            return redirect(student_dashboard)
        else:
            return redirect(student_login)
    return render(r, 'login.html')


def student_dashboard(r):
    if not r.session.has_key('student_log'):
        return redirect(student_login)


    roll = (Student.objects.get(email=r.session['student_log'])).roll

    # checking course

    if StudentCourse.objects.filter(student_id=roll).exists()==False:
        alert = 1


#############
    cond = Q(payment_student_id=roll) & Q(payment_status=0)
    data = {
        "student": Student.objects.filter(roll =roll),
        'payment': Payment.objects.filter(payment_student_id=roll),
        'student_course': StudentCourse.objects.filter(student_id=roll),
        'due': Payment.objects.filter(cond).aggregate(Sum('payment_amount')),
        'emptycourse':alert
    }
    return render(r, 'student/student_dashboard.html',data)


def student_course(r):
    if not r.session.has_key('student_log'):
        return redirect(student_login)
    log = r.session['student_log']
    std = Student.objects.get(email=log).roll
    data = {
        'studentcourse': StudentCourse.objects.filter(student_id=std),
        'student':Student.objects.filter(roll=std)
    }
    return render(r,'student/student_course.html',data)


def student_payment(r):
    roll = (Student.objects.get(email=r.session['student_log'])).roll
    cond = Q(payment_student_id=roll) & Q(payment_status=0)
    data = {
        "student": Student.objects.filter(roll=roll),
        'payment': Payment.objects.filter(payment_student_id=roll),
        'student_course': StudentCourse.objects.filter(student_id=roll),
        'due': Payment.objects.filter(cond).aggregate(Sum('payment_amount'))
    }
    if not r.session.has_key('student_log'):
        return redirect(student_login)

    std = Student.objects.filter(email=r.session['student_log'])
    doa = std[0].date_of_creation.month
    current_month = timezone.now().month
    print(doa)
    for x in range(doa,current_month+1):
        if Payment.objects.filter(payment_month=x).exists()==False:
            p = Payment()
            p.payment_month = x
            p.payment_student_id = Student(std[0].roll)
            p.payment_amount = 700
            p.payment_doc = timezone.now()
            p.payment_status = 0
            p.save()

    return render(r, 'student/student_payment.html',data)


def student_setting(r):
    return render(r, 'student/student_setting.html')


def logout(r):
    if r.session.has_key('student_log'):
        del r.session['student_log']
    return redirect(student_login)


def payment_done(r, pay_id):
    p = Payment.objects.get(pay_id=pay_id)
    p.payment_status = 1
    p.save()
    return redirect(student_dashboard)

templates/apply.html
{% extends 'base.html' %}
{% block side %}

{% endblock %}
{% block content %}
    <div class="container mt-3">
        <form action="{% url 'apply' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row ">
                {% for foo in insert_form %}
                    <div class="col-lg-6">
                        <div class="form-group">
                            {{ foo.label_tag }}
                            {{ foo }}
                            <p class="small">{{ i.error }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>

            <div class="form-group">
                <input type="submit" class="btn btn-success btn-block">
            </div>
        </form>
    </div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>CMS</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap.css' %}">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-3">
        <h2 class="display-4 text-uppercase mt-3 text-center">EduTech</h2>
            {% block side %}{% endblock %}
        </div>
        <div class="col-lg-9 p-0">
            <nav class="navbar navbar-expand-lg navbar-dark bg-primary shadow-sm">
                <ul class="navbar-nav mx-auto">
                    <li class="navbar-item mx-4"><a href="{% url 'homepage' %}" class="nav-link text-light">Home</a></li>
                    <li class="navbar-item mx-4"><a href="" class="nav-link text-light">About</a></li>
                    <li class="navbar-item mx-4"><a href="" class="nav-link text-light">Contact</a></li>
                    <li class="navbar-item mx-4"><a href="{% url 'apply' %}" class="nav-link text-light">Admission</a></li>
                    <li class="navbar-item mx-4"><a href="{% url 'student_login' %}" class="nav-link text-light">Student Login</a></li>
                </ul>
            </nav>
            {% block content %}{% endblock %}
        </div>
    </div>
</div>
{% block footer %}{% endblock %}
<div class="container-fluid text-center">
    <p class="small">Design by CWS</p>
</div>
<script>
    $(document).ready(function () {
        $("input, select, textarea").addClass("form-control")
    });
</script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

templates/login.html
{% extends 'base.html' %}


{% block content %}
    <div class="container">
    <div class="row my-5">
        <div class="col-lg-5 mx-auto">
            <div class="card">
                <div class="card-body">
                    <form action="{% url 'student_login' %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="p-0 m-0 small text-muted">Email/User/Phone</label>
                            <input type="text" class="form-control" name="email">
                        </div>
                        <div class="form-group">
                            <label class="p-0 m-0 small text-muted">Password</label>
                            <input type="password" class="form-control" name="password">
                        </div>
                        <div class="form-group">
                            <input type="submit" class="btn btn-success">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock %}

templates/student/student_base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>CMS | Student Panel</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap.css' %}">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-3 my-3">
            <img src="{{ student.0.dp.url }}" class="w-100" height="auto">
            <div class="list-group mt-3">
                <a href="{% url 'student_dashboard' %}" class="list-group-item list-group-item-action">Dashboard</a>
                <a href="{% url 'student_payment' %}" class="list-group-item list-group-item-action">Manage Payment</a>
                <a href="{% url 'student_course' %}" class="list-group-item list-group-item-action">Manage Course</a>
                <a href="{% url 'student_setting' %}" class="list-group-item list-group-item-action">Profile Setting</a>
            </div>
            {% block side %}{% endblock %}
        </div>
        <div class="col-lg-9 p-0">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow-sm">
                <a href="" class="navbar-brand">EduTech Management System</a>
                <ul class="navbar-nav ml-auto">
                    <li class="navbar-item mx-4">
                        <a href="{% url 'student_logout' %}" class="btn btn-danger btn-sm">LogOut</a>
                    </li>
                </ul>
            </nav>
            {% block content %}{% endblock %}
        </div>
    </div>
</div>
{% block footer %}{% endblock %}
<div class="container-fluid text-center">
    <p class="small">Design by CWS</p>
</div>
<script>
    $(document).ready(function () {
        $("input, select, textarea").addClass("form-control")
    });
</script>
</body>
</html>

templates/student/student_course.html
{% extends 'student/student_base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <table class="table">
                <tr>
                    <th>StudentCourse Id</th>
                    <th>Student Name</th>
                    <th>Course Name</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
                {% for sc in studentcourse %}
                    <tr>
                        <td>{{ sc.id }}</td>
                        <td>{{ sc.student_id.full_name }}</td>
                        <td>{{ sc.student_id.course_title }}</td>
                        <td>{{ sc.type }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}

templates/student/student_course_add.html
{% extends 'student/student_base.html' %}

{% block content %}
    <div class="container">

        <div class="row">
            <form action="" method="post">
                {{ studentcourseform }}
            </form>
        </div>
    </div>
{% endblock %}

templates/student/student_dashboard.html
{% extends 'student/student_base.html' %}

{% block content %}

    <div class="container">
        {% if emptycourse == 1 %}
            <div class="alert alert-danger mt-3">
                <h1 class="lead d-inline-block">Course is empty please add</h1>
                <a href="" class="btn btn-primary ml-4">Add course</a>
            </div>
        {% endif %}
    </div>
    <div class="jumbotron rounded-0">
        <h2 class="text-capitalize">welcome {{ student.0.full_name }}</h2>
        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid cumque, cupiditate debitis distinctio est facilis ipsa itaque mollitia obcaecati odit quaerat quas repudiandae sint sit tenetur. Accusamus aperiam inventore quibusdam.</p>
    </div>
    <div class="container">
    <div class="row">
        <div class="col-lg-12">

        </div>
        <div class="col-lg-6">
            <div class="card">
                <div class="card-body">
                    <h2>Recent Payments</h2>
                </div>
                <table class="table">
                    <tr>
                        <th>Pay ID</th>
                        <th>Amount</th>
                        <th>Month</th>
                        <th>Status</th>
                    </tr>
                    {% for p in payment %}
                    <tr>
                        <td>{{ p.pay_id }}</td>
                        <td>{{ p.payment_amount }}</td>
                        <td>{{ p.get_payment_month_display }}</td>
                        <td>
                            {% if p.payment_status == 0 %}
                                <a href="{% url 'student_payment_done' p.pay_id %}" class="btn btn-success btn-sm">Pay Now</a>
                            {% else %}
                                <a href="" class="btn btn-info btn-sm disabled">Paid</a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="row">
                <div class="col-lg-6">
                    <div class="card bg-info text-white">
                        <div class="card-body">
                            <h2 class="display-4">
                                {{ due.payment_amount__sum }}/-
                            </h2>
                            <p class="small">Total Dues</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="card bg-warning">
                        <div class="card-body">
                            <h2 class="display-4">2</h2>
                            <p class="small">Total Course</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock %}

templates/student/student_payment.html
{% extends 'student/student_base.html' %}

{% block content %}
    <div class="container">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <h2>Recent Payments</h2>
                </div>
                <table class="table">
                    <tr>
                        <th>Pay ID</th>
                        <th>Amount</th>
                        <th>Month</th>
                        <th>Status</th>
                    </tr>
                    {% for p in payment %}
                    <tr>
                        <td>{{ p.pay_id }}</td>
                        <td>{{ p.payment_amount }}</td>
                        <td>{{ p.get_payment_month_display }}</td>
                        <td>
                            {% if p.payment_status == 0 %}
                                <a href="{% url 'student_payment_done' p.pay_id %}" class="btn btn-success btn-sm">Pay Now</a>
                            {% else %}
                                <a href="" class="btn btn-info btn-sm disabled">Paid</a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/student/student_setting.html
{% extends 'student/student_base.html' %}